name: ci-cd test

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      #github actions에서 빌드를 수행하고 ec2로 빌드된 데이터를 넘김
      - name: Github repository에 올린 파일들 불러오기
        uses: actions/checkout@v4 #레포지토리의 파일들을 불러오는 라이브러리

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 저장
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          source: project.jar
          target: /home/ubuntu/seahee.baek_fork/scp

      # ec2에 접속
      - name: SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script:
            rm -rf /home/ubuntu/seahee.baek_fork/current
            mkdir /home/ubuntu/seahee.baek_fork/current
            mv /home/ubuntu/seahee.baek_fork/scp/project.jar /home/ubuntu/seahee.baek_fork/current/project.jar
            cd /home/ubuntu/seahee.baek_fork/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar project.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/seahee.baek_fork/scp


